model: "debug"
dns_port: "1053"
api_port: "18080"

log:
  level: "info"
  output: "stdout"
  file: "./tdns2socks.log"

proxy_default:
  server: "172.18.2.1"
  port: 53
  protocol: "udp"
  username: "LianO"
  password: "LianO2024"
  upstream: "114.114.114.114:53"